services:
  - type: cron
    name: mcfox-autoscale
    env: ruby
    plan: Starter
    schedule: "*/30 * * * *"
    buildCommand: "gem install bundler; bundle install"
    startCommand: "bundle exec ruby run.rb"
