services:
  - type: cron
    name: recovery2_prod_autoscale_v2
    env: ruby
    region: ohio
    plan: Starter
    schedule: "*/30 * * * *"
    buildCommand: "gem install bundler; bundle install"
    startCommand: "bundle exec ruby run.rb"
    envVars:
      - key: AUTOSCALE_SERVICE_NAME
        value: "recovery2_prod_worker"
      - key: SIDEKIQ_RENDER_AUTOSCALE_API_TOKEN
        value: "rnd_M57RvdKsIGwYoGBf8FpmnzVA0ku2"
      - key: SIDEKIQ_MAX_WORKERS
        value: "2"
      - key: REDIS_URL
        fromService:
          type: redis
          name: recovery2_prod_redis
          property: connectionString